[tool.poetry]
name = "ai"
version = "0.1.0"
description = ""
authors = ["vitaliy <vitaliy>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openai = "^0.27.2"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

